# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5963f34649893625aef7e8d8ba33e0940a5c70eed718e25006a7d7370a3e65da11635cdd77c2ce964661ae30a51fe0dc8f238a39054e4f5e78e91d45f8d8762c

test:
  secret_key_base: e5b8cf852af02d89694ad98f1d544d1be6a5a0e0f2ecb1b29275d0256503a9c9fc8e33948691dd78a4619ae3727e71f3666720a544770c9a3f72e57687039c21

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
